import { FC } from "react";
import Head from "next/head";
import { Footer, Navbar } from "../ui";





interface Props {
  title: string;
}

export const AdminLayout: FC<Props> = ({ children, title }) => {

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Navbar />


        <main className="bg-white-seguro container mx-auto mt-5">
            {children}
        </main>

        <Footer/>
    </>
  );
};
