import { FC } from "react";
import Head from "next/head";
import Image from 'next/image'

interface Props {
  title: string;
}

import React from 'react'
import { Footer } from "../ui";

export const AuthLayout: FC<Props> = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen w-full flex flex-col">

        <div className="flex-grow border">
          {/* <main className="container mx-auto mt-5 ">{children}</main> */}
          {children}
        </div>
        <Footer />
      </div>
    </>
  );
}

export default AuthLayout;
