import { FC } from "react";
import Head from "next/head";
import { Footer, Navbar } from "../ui";

interface Props {
  title: string;
}

export const PublicLayout: FC<Props> = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen w-full flex flex-col">
        <Navbar />

        <div className="flex-grow">
          <main className="container mx-auto mt-5">{children}</main>
        </div>
        <Footer />
      </div>
    </>
  );
};
